### ISSUE TITLE
Plugin Needs Polling to Determine Status

### ISSUE THREAD

**Issue by MoTechnicalities** [kpsuperplane/homebridge-wiz-lan#47]
HomeKit does not update the bulb status unless you leave the room or app and come back.
My test:
- Go into HomeKit Room and turn on light using bulb icon.
- physically turn off power to bulb.

Result:
Icon never changes until I exit the HomeKit room then re-enter. Same if I start with a "no response" bulb and power it on. The status doesn't update until I exit the HomeKit room and re-enter.

**Comment by kpsuperplane** [comment]
Polling unfortunately results in a large amount of network traffic that is most likely detrimental to the experience of other devices of the network. 

The reason this works fine in the Wiz app is because the app "subscribes" to the bulbs only when the app is open. However, I don't believe HomeBridge lets me know when the plugin should be subscribing to the bulbs. 

I'm open to suggestions here but I don't believe subscribing to the bulbs 24/7 is a good solution for the vast majority of users.

**Comment by MoTechnicalities** [comment]
With homebridge-wiz-lan v3.0.2 performance is now greatly improved, so for now, I'll just be happy with what we've got. Thanks.
