### ISSUE TITLE
Multiple wiz lights in each room

### ISSUE THREAD

**Issue by lcslouis** [kpsuperplane/homebridge-wiz-lan#85]
Hello I have a configuration that has multiple wiz lights in each room. 

Room 1: 4 lights
Room 2: 6 lights 
Room 3: 4 lights 

Homekit won't allow the grouping unless I separate a bulb in 2 tiles and then group them. 

I'm thinking this is because apple thinks they are not the same model light. Can this be fixed to where that isn't an issue anymore?

**Comment by MoTechnicalities** [comment]
This is because the new scene selection feature of the plugin already groups the bulb with a "service".

HomeKit so far, does not allow groups of groups.

I decided to turn the new scene feature off due to the added reason that Quick Tile Press opens the accessory's setting, instead of just turning ON/OFF the light. It is poor interface design that Apple has set both Quick Press and Long Press to open a Tile with embedded services to the device settings.

**Comment by MoTechnicalities** [comment]
After experimenting, I found that even if you retain the new Scene feature, you can still group lights with other lights if you first ungroup them individually from their Scene service tile.
You can give the Service Tile the same name as the light. You will then be able to use the group tile and/or the individual service Tile to turn ON/OFF you lights!😀👍👍
